# Generated by Django 4.2.30 on 2026-04-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companydepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranchinfo',
            name='company_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companycontactinfo'),
        ),
    ]
