# Generated by Django 4.2.30 on 2026-07-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companybranchinfo_company_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybranchinfo',
            name='company_contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companycontactinfo'),
        ),
    ]
