# Generated by Django 5.2.7 on 2025-10-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userauthentication',
            name='is_super_admin',
        ),
    ]
