# Generated by Django 5.2.7 on 2025-10-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userauthentication_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthentication',
            old_name='is_contarctor',
            new_name='is_contractor',
        ),
    ]
