# Generated by Django 5.2.7 on 2025-10-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_is_contarctor_userauthentication_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userauthentication',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
