# Generated by Django 4.2.30 on 2026-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userauthentication_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userauthentication',
            old_name='user_registation_status',
            new_name='user_registration_status',
        ),
        migrations.RenameField(
            model_name='usercredentialvalidation',
            old_name='user_registation_status',
            new_name='user_registration_status',
        ),
    ]
