# Generated by Django 4.2.30 on 2026-04-09 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0005_rename_user_registation_status_userauthentication_user_registration_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
