# Generated by Django 4.2.30 on 2026-07-07 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0007_alter_userauthentication_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbaseconfig',
            name='bypass_password',
            field=models.CharField(blank=True, default='fallback_pass', max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
