# Generated by Django 5.2.7 on 2025-11-05 06:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_userdesignation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLocationInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('is_default', models.BooleanField(default=True)),
                ('address_id', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line_01', models.CharField(blank=True, max_length=70, null=True)),
                ('address_line_02', models.CharField(blank=True, max_length=70, null=True)),
                ('mobile_number_01', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number_02', models.CharField(blank=True, max_length=20, null=True)),
                ('communication_address', models.CharField(blank=True, max_length=220, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=220, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('google_place_link', models.CharField(blank=True, max_length=220, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='joblist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('description', models.CharField(blank=True, max_length=220, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=8, null=True)),
                ('vacancies', models.CharField(blank=True, max_length=8, null=True)),
                ('budget', models.CharField(blank=True, max_length=15, null=True)),
                ('expried_date', models.DateTimeField(auto_now=True)),
                ('provider_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblocationinfo')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
