# Generated by Django 5.2.7 on 2025-11-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobdocument_joblist_photo_jobdetails'),
        ('users', '0004_userdesignation_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='authentication',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='company_branch',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='joblist',
            name='provider_info',
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='provider_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo'),
        ),
    ]
