# Generated by Django 5.2.7 on 2025-11-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobdetails_authentication_and_more'),
        ('users', '0004_userdesignation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='provider_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo'),
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
    ]
