# Generated by Django 5.2.7 on 2025-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_joblist_provider_info_delete_jobdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='expried_date',
            field=models.DateTimeField(null=True),
        ),
    ]
