# Generated by Django 5.2.7 on 2025-11-11 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joblist_expried_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='joblocationinfo',
            name='address_line_02',
        ),
        migrations.RemoveField(
            model_name='joblocationinfo',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='joblocationinfo',
            name='communication_address',
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='job_document'),
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joblist',
            name='attachments',
            field=models.ManyToManyField(to='jobs.jobdocument'),
        ),
        migrations.AddField(
            model_name='joblist',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblist',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblist',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joblist',
            name='reference_name',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
