# Generated by Django 5.2.7 on 2025-11-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_joblist_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='raised_by',
        ),
    ]
