# Generated by Django 5.2.7 on 2025-11-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_joblist_raised_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly wages'), ('daily', 'Daily wages')], default='daily', max_length=10),
        ),
    ]
