# Generated by Django 5.2.7 on 2025-11-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_joblist_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='position',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
