# Generated by Django 5.2.7 on 2025-11-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_joblist_description_alter_joblist_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly wages'), ('daily', 'Daily wages'), ('hourly', 'Hourly wages'), ('contractor', 'Contactor-based')], default='', max_length=100),
        ),
    ]
