# Generated by Django 5.2.7 on 2025-11-12 07:09

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_joblist_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='salary_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('monthly', 'Monthly wages'), ('daily', 'Daily wages'), ('hourly', 'Hourly wages'), ('contractor', 'Contactor-based')], default='', max_length=100),
        ),
    ]
