# Generated by Django 5.2.7 on 2025-11-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_joblist_salary_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='salary_type',
            new_name='payment_type',
        ),
    ]
