# Generated by Django 5.2.7 on 2025-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_jobapplication_status_jobapplicationstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=200, null=True),
        ),
    ]
