# Generated by Django 5.2.7 on 2025-11-21 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joblist'),
        ),
    ]
