# Generated by Django 4.2.30 on 2026-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_jobdetails_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='expection_rate',
            new_name='expected_rate',
        ),
        migrations.RenameField(
            model_name='joblist',
            old_name='expried_date',
            new_name='expiry_date',
        ),
    ]
