# Generated by Django 5.2.7 on 2025-10-18 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userauthentication_is_admin_and_more'),
        ('company', '0003_companydepartment'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=40, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_document')),
                ('token', models.TextField(blank=True, null=True)),
                ('is_token_valid', models.BooleanField(default=False)),
                ('authentication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.userauthentication')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymeta')),
                ('company_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companybranchinfo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companydepartment')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userdesignation')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_referrer', to='users.employeecompanyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
