# Generated by Django 5.2.7 on 2025-10-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employeecompanyinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdesignation',
            old_name='is_client',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='userdesignation',
            old_name='is_contarctor',
            new_name='is_job_seeker',
        ),
        migrations.RemoveField(
            model_name='userdesignation',
            name='is_faculty',
        ),
    ]
