# Generated by Django 5.2.7 on 2025-10-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companydepartment'),
        ('users', '0003_rename_is_client_userdesignation_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesignation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companymeta'),
        ),
        migrations.AddField(
            model_name='userdesignation',
            name='company_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companybranchinfo'),
        ),
    ]
