# Generated by Django 5.2.7 on 2025-11-21 06:10

import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userdesignation_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfessionalInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, max_length=210, null=True)),
                ('custom_field', models.JSONField(blank=True, default=dict, null=True)),
                ('Experience', models.IntegerField(default=0)),
                ('available_days_category', models.CharField(choices=[('weekdays', 'Weekdays (Mon-Fri)'), ('weekend', 'Weekend (Sat-Sun)'), ('custom', 'Custom days')], default='weekdays', max_length=10)),
                ('custom_days', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=13, null=True)),
                ('portfolio_photo', models.ImageField(blank=True, null=True, upload_to='portfolio_photos/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
