# Generated by Django 5.2.7 on 2025-11-21 06:19

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofessionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofessionalinfo',
            name='available_days_category',
            field=models.CharField(choices=[('weekday', 'Weekdays (Mon–Fri)'), ('weekend', 'Weekend (Sat–Sun)'), ('custom', 'Custom Days')], default='weekday', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofessionalinfo',
            name='custom_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=27, null=True),
        ),
    ]
