# Generated by Django 5.2.7 on 2025-11-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofessionalinfo_available_days_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofessionalinfo',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.employeecompanyinfo'),
        ),
    ]
