# Generated by Django 5.2.7 on 2025-11-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofessionalinfo_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofessionalinfo',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
