# Generated by Django 5.2.7 on 2025-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofessionalinfo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofessionalinfo',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofessionalinfo',
            name='position',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='userprofessionalinfo',
            name='skills',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
