# Generated by Django 5.2.7 on 2025-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofessionalinfo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofessionalinfo',
            name='available_days_category',
            field=models.CharField(choices=[('weekday', 'Weekdays (Mon–Fri)'), ('weekend', 'Weekend (Sat–Sun)'), ('custom', 'Custom Days')], default='', max_length=20),
        ),
    ]
