# Generated by Django 4.2.30 on 2026-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofessionalinfo_available_days_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofessionalinfo',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='userprofessionalinfo',
            old_name='Experience',
            new_name='experience',
        ),
    ]
